const ERROR_CODE_SUCCESS = 200;
const ERROR_CODE_SYSTEM_ERROR = 500;
const ERROR_CODE_UNAUTHORIZED = 401;
const ERROR_CODE_FORBIDDEN = 403;
const ERROR_CODE_TOKEN_EXPIRED = 402;
const ERROR_CODE_API_NOT_FOUND = 404;
const ERROR_CODE_UPLOAD_ERROR = 409;
const ERROR_CODE_INVALID_PARAMETER = 422;
const ERROR_CODE_INCORRECT_PASSWORD = 303;
const ERROR_CODE_CREDENTIAL_NOT_EXIST = 304;
const ERROR_CODE_OLD_PASSWORD_NOT_CORRECT = 305;
const ERROR_CODE_EMAIL_EXIST = 306;
const ERROR_CODE_ITEM_NOT_EXIST = 308;
const ERROR_CODE_CHANGE_STATUS_NOT_SUCCESS = 309;
const ERROR_CODE_IMPORT_CSV_FAIL = 310;
const ERROR_BAD_REQUEST = 400
const ERROR_I_AM_A_TEA_POT = 418
const ERROR_TOO_MANY_REQUEST = 429

module.exports = {
    ERROR_CODE_SUCCESS,
    ERROR_CODE_SYSTEM_ERROR,
    ERROR_CODE_UNAUTHORIZED,
    ERROR_CODE_FORBIDDEN,
    ERROR_CODE_TOKEN_EXPIRED,
    ERROR_CODE_API_NOT_FOUND,
    ERROR_CODE_UPLOAD_ERROR,
    ERROR_CODE_INVALID_PARAMETER,
    ERROR_CODE_INCORRECT_PASSWORD,
    ERROR_CODE_CREDENTIAL_NOT_EXIST,
    ERROR_CODE_OLD_PASSWORD_NOT_CORRECT,
    ERROR_CODE_EMAIL_EXIST,
    ERROR_CODE_ITEM_NOT_EXIST,
    ERROR_CODE_CHANGE_STATUS_NOT_SUCCESS,
    ERROR_CODE_IMPORT_CSV_FAIL,
    ERROR_BAD_REQUEST,
    ERROR_I_AM_A_TEA_POT,
    ERROR_TOO_MANY_REQUEST
}